# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  foxo_config = debug
endif
ifeq ($(config),release)
  foxo_config = release
endif

PROJECTS := foxo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

foxo:
ifneq (,$(foxo_config))
	@echo "==== Building foxo ($(foxo_config)) ===="
	@${MAKE} --no-print-directory -C foxo -f Makefile config=$(foxo_config)
endif

clean:
	@${MAKE} --no-print-directory -C foxo -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   foxo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"